import { Router, type IRouter } from "express";
import { adminAuth } from "../middleware/admin-auth";
import healthRouter from "./health";
import leadsRouter from "./leads";
import tasksRouter from "./tasks";
import templatesRouter from "./templates";
import assetsRouter from "./assets";
import dashboardRouter from "./dashboard";
import syncRouter from "./sync";
import contactsRouter from "./contacts";
import campaignsRouter from "./campaigns";
import templateSetsRouter from "./template-sets";
import sequenceRouter from "./sequence";
import outboundRouter from "./outbound";
import scheduledEmailsRouter from "./scheduled-emails";
import notificationsRouter from "./notifications";
import engagementEventsRouter from "./engagement-events";
import bulkSendRouter from "./bulk-send";
import inboundEmailRouter from "./inbound-email";
import partnersRouter from "./partners";
import partnerRequestsRouter from "./partner-requests";
import pricingRulesRouter from "./pricing-rules";
import outlookRouter from "./outlook";
import companiesRouter from "./companies";
import replyReviewRouter from "./reply-review";
import settingsRouter from "./settings";
import seedRouter from "./seed-templates";

const router: IRouter = Router();

router.use(healthRouter);
router.use(leadsRouter);
router.use(tasksRouter);
router.use(templatesRouter);
router.use(assetsRouter);
router.use(dashboardRouter);
router.use(syncRouter);
router.use(contactsRouter);
router.use(campaignsRouter);
router.use(templateSetsRouter);
router.use(sequenceRouter);
router.use(outboundRouter);
router.use(scheduledEmailsRouter);
router.use(notificationsRouter);
router.use(engagementEventsRouter);
router.use(bulkSendRouter);
router.use(inboundEmailRouter);
router.use(partnersRouter);
router.use(partnerRequestsRouter);
router.use(pricingRulesRouter);

router.use(adminAuth, outlookRouter);
router.use(adminAuth, companiesRouter);
router.use(adminAuth, replyReviewRouter);
router.use(adminAuth, settingsRouter);
router.use(adminAuth, seedRouter);

export default router;
